---
title: "CNV Heatmaps"
author: "Prachi Shukla"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---


```{r libraries, message=FALSE}

library(ggplot2)
library(data.table)
library(tidyverse)
library(patchwork)
library(RColorBrewer)
library(viridisLite)
library(scales)
library(qs2)
library(Seurat)
library(SCpubr)
library(ComplexHeatmap)
library(ggsci)
library(ggpubr)

knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE)

theme_set(theme_classic())


cnv_label = c("Ref" = "#303030", "Metastasis" = "#ef767a", "Primary" = "#5A83AF", "Healthy" = "#49beaa")
curr_label = c("Other" = "#7e77bb", "Current" = "#F5EA62")

cnv_cluster_cols = setNames(c(brewer.pal(n = 12, name = "Set3"), "#303030"), as.character(0:12))

rna_cluster_cols = c("#1F77B4FF", "#FF7F0EFF", "#2CA02CFF", "#D62728FF", "#9467BDFF", "#8C564BFF", "#E377C2FF", "#7F7F7FFF", "#BCBD22FF", "#17BECFFF", "#AEC7E8FF", "#FFBB78FF", "#98DF8AFF", "#FF9896FF", "#C5B0D5FF", "#C49C94FF", "#F7B6D2FF", "#C7C7C7FF", "#DBDB8DFF", "#9EDAE5FF")



```


```{r functions}
inferCNVHeatmapsCNV <- function(expr_df, meta, RNA_cluster_cols, genes, base_size = 12, samp_id = NULL){
  
  # Arrange cells by cluster 
  clusters = meta %>% select(sample_barcode, seurat_clusters, seurat_clusters_Merged, inferCNV_label, Curr_Samp) %>% 
    arrange(seurat_clusters, seurat_clusters_Merged, inferCNV_label, Curr_Samp)
  
  chr_levels <- paste0("chr", c(1:22))
  
  chr_palette = setNames(c('#4ECCAC', '#1d1d1d', '#ebce2b', '#702c8c', '#db6917', 
                           '#96cde6', '#ba1c30', '#c0bd7f', '#7f7e80', '#5fa641', 
                           '#d485b2', '#4277b6', '#df8461', '#463397', '#e1a11a', 
                           '#91218c', '#e8e948', '#7e1510', '#92ae31', '#6f340d', 
                           '#d32b1e', '#2b3514'),
                         chr_levels
  )
  
  gene_chr <- genes$chr[match(rownames(expr_df), genes$gene)]
  gene_chr <- factor(gene_chr, levels = chr_levels)
  ha_bottom <- HeatmapAnnotation(
    Chromosome = gene_chr,
    col = list(Chromosome = chr_palette),
    which = "column",
    annotation_name_side = "left",
    annotation_name_gp = gpar(fontsize = base_size),
    annotation_legend_param = list(
      Chromosome = list(
        title = "Chr",
        ncol = 1,
        title_gp = gpar(fontsize = base_size + 1, fontface = "bold"),
        labels_gp = gpar(fontsize = base_size)
      )
    )
  )
  
  df = t(expr_df[, clusters$sample_barcode])
  
  # Most common number
  mode_df = as.data.table(table(df[, 1])) %>% mutate(number = as.double(V1))
  middle = filter(mode_df, N == max(N)) %>% pull(number)
  range_df = range(df)
  
  hma = rowAnnotation(
    `CNV Clusters` = clusters$seurat_clusters,
    `RNA Clusters` = clusters$seurat_clusters_Merged,
    `Label` = clusters$inferCNV_label,
    `Current Sample` = clusters$Curr_Samp,
    col = list(
      `CNV Clusters` = cnv_cluster_cols[unique(clusters$seurat_clusters)],
      `RNA Clusters` = RNA_cluster_cols,
      `Label` = cnv_label[unique(clusters$inferCNV_label)],
      `Current Sample` = curr_label[unique(clusters$Curr_Samp)]
    ),
    annotation_name_gp = gpar(fontsize = base_size),
    annotation_legend_param = list(
      `CNV Clusters` = list(
        title = "CNV\nClusters",
        ncol = 1,
        title_gp = gpar(fontsize = base_size + 1, fontface = "bold"),
        labels_gp = gpar(fontsize = base_size)
      ),
      `RNA Clusters` = list(
        title = "RNA\nClusters",
        ncol = 1,
        title_gp = gpar(fontsize = base_size + 1, fontface = "bold"),
        labels_gp = gpar(fontsize = base_size)
      ),
      `Label` = list(
        title = "Label",
        ncol = 1,
        title_gp = gpar(fontsize = base_size + 1, fontface = "bold"),
        labels_gp = gpar(fontsize = base_size)
      ),
      `Current Sample` = list(
        title = "Current\nSample",
        ncol = 1,
        title_gp = gpar(fontsize = base_size + 1, fontface = "bold"),
        labels_gp = gpar(fontsize = base_size)
      )
    )
  )
  
  # Remvoe labels
  rownames(df) <- NULL
  colnames(df) <- NULL
  
  
  if(!range_df[1] == 1){
    expression = circlize::colorRamp2(breaks = c(range_df[1], middle, range_df[2]), 
                                      colors = c("#00428c", "white", "#9e002a"))
    
  }else{
    expression = circlize::colorRamp2(breaks = c(range_df[1], range_df[2]), 
                                      colors = c("white", "#9e002a"))
  }
  
  gene_chr_nolabel <- gene_chr
  lvl <- levels(gene_chr_nolabel)
  
  # make unique invisible titles using zero-width spaces
  invis <- vapply(seq_along(lvl), function(i) paste(rep("\u200B", i), collapse = ""), character(1))
  levels(gene_chr_nolabel) <- invis
  
  Heatmap(df, name = paste0(samp_id, "\ninferCNV\nExpr"), 
          border_gp = gpar(col = "#a6a6a6"),
          right_annotation = hma, 
          bottom_annotation = ha_bottom,
          use_raster = TRUE, cluster_columns = FALSE,
          cluster_rows = FALSE,
          col = expression, 
          column_split = gene_chr_nolabel,
          column_gap   = grid::unit(0.5, "pt"),
          column_title = NULL,
          heatmap_legend_param = list(
            ncol = 1,
            title_gp = gpar(fontsize = base_size + 1, fontface = "bold"),
            labels_gp = gpar(fontsize = base_size)
          ))
}


```

# Heatmaps

```{r loading_files}

################
# CNV Heatmaps #
################

# so_list = qs_read("../20251023_so_cnv_list.qs2", nthreads = 40)
# expr = qs_read("../20251023_infercnv_expr_list.qs2")

samps = c("395751_40-hCh25_GEX_H9", 
          "373191_05-pUM11_GEX_G3", 
          "395751_39-pUM25_GEX_H8", 
          "395751_12-mUM04_GEX_F5", 
          "395751_13-mUM05_GEX_F6")

# so_list = so_list[samps]
# expr = expr[samps]
# qs_save(so_list, "../20260415_so_cnv_list_final_red.qs2")
# qs_save(expr, "../20260415_infercnv_expr_list_final_red.qs2")

so_list = qs_read("../20260415_so_cnv_list_final_red.qs2")
expr = qs_read("../20260415_infercnv_expr_list_final_red.qs2")

genes = qs_read("../20251024_HMM_gene_CNV_all.qs2")
genes = rbindlist(genes) %>% select(gene, chr, start, end)
# keep one record per gene (take first chr, min start / max end)
genes <- genes[
  , .(chr = chr[1L],
      start = min(start, na.rm = TRUE),
      end   = max(end,   na.rm = TRUE)),
  by = gene
]

# keep only standard chromosomes and order them properly
chr_levels <- paste0("chr", c(1:22))
genes <- genes[chr %in% chr_levels]
genes[, chr := factor(chr, levels = chr_levels)]
setorder(genes, chr, start)



```

## Plots

```{r, fig.width=18, fig.height=15, results='asis'}

pdf("final_heatmaps.pdf", width = 18, height = 15)

for(i in names(so_list)){
  
  # Standardizing RNA cluster colors
  cluster_colors = setNames(rna_cluster_cols[1:uniqueN(so_list[[i]]$seurat_clusters_Merged)], 
                            sort(unique(so_list[[i]]$seurat_clusters_Merged)))
  origin_temp = so_list[[i]]@meta.data %>% filter(Curr_Samp == "Current") %>% pull(origin) %>% unique()
  
  so_list[[i]]$inferCNV_label = str_to_sentence(so_list[[i]]$inferCNV_label)
  
  samp_id_curr = gsub(".*-(.*)_GEX.*", "\\1", i)
  
  # cat("##", i, "\n\n")
  
  ht = inferCNVHeatmapsCNV(expr[[i]], meta = so_list[[i]]@meta.data, RNA_cluster_cols = cluster_colors,  
                           genes = genes, base_size = 13, samp_id = samp_id_curr)
draw(
  ht,
  heatmap_legend_side = "right",
  annotation_legend_side = "right",
  merge_legends = TRUE
)
    

# cat("\n\n")
  
}

dev.off()

```

